[workspace]
resolver = "3"
members = [
    "crates/zkevm-prof",
    "crates/zkvm-prof",
]

[workspace.package]
version = "0.3.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
cargo_metadata = "0.23"
clap = { version = "4", features = ["derive"] }
gag = "1"
hex = "0.4"
rayon = "1"
regex = "1"
reqwest = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
walkdir = "2"

# ere
ere-dockerized = { git = "https://github.com/eth-act/ere", tag = "v0.17.0" }

# ere-guests
stateless-validator-catalog = { git = "https://github.com/eth-act/ere-guests", tag = "v0.16.0" }
stateless-validator-downloader = { git = "https://github.com/eth-act/ere-guests", tag = "v0.16.0" }

# local
zkvm-prof = { path = "crates/zkvm-prof" }
