[package]
name = "zkevm-prof"
version.workspace = true
edition.workspace = true

[dependencies]
zkvm-prof.workspace = true

anyhow.workspace = true
clap.workspace = true
gag.workspace = true
hex.workspace = true
rayon.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
stateless-validator-catalog.workspace = true
stateless-validator-downloader.workspace = true
tokio.workspace = true
walkdir.workspace = true

[build-dependencies]
cargo_metadata.workspace = true
