name: Profile SP1

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  profile:
    uses: ./.github/workflows/profile.yml
    permissions:
      contents: write
    with:
      zkvm: sp1
